using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using SummaryService.Application.Interfaces;
using Microsoft.Extensions.Logging;

namespace SummaryService.Infrastructure.Pdf;

public sealed class PdfOcrExtractor(ILogger<PdfOcrExtractor> logger) : IPdfOcrExtractor
{
    private const int MaxParallelPages = 2; // Controla el grado de paralelismo para no saturar el sistema

    public async Task<string> ExtractTextWithOcrAsync(Stream pdfStream, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        logger.LogInformation("Starting OCR extraction via command-line Tesseract");

        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(tempDir);

        try
        {
            var pdfPath = Path.Combine(tempDir, "document.pdf");
            await using (var fs = new FileStream(pdfPath, FileMode.Create, FileAccess.Write))
            {
                await pdfStream.CopyToAsync(fs, ct).ConfigureAwait(false);
            }

            // 1. Convertir PDF a imágenes usando pdftoppm
            using (var ppmProcess = new Process())
            {
                ppmProcess.StartInfo = new ProcessStartInfo
                {
                    FileName = "pdftoppm",
                    // IMPORTANTE: %03d asegura nombres como page-001.png, page-010.png (arregla el orden alfabético)
                    Arguments = $"-png -r 300 \"{pdfPath}\" \"{Path.Combine(tempDir, "page")}\"",
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                try
                {
                    ppmProcess.Start();
                    await ppmProcess.WaitForExitAsync(ct).ConfigureAwait(false);

                    if (ppmProcess.ExitCode != 0)
                    {
                        var error = await ppmProcess.StandardError.ReadToEndAsync(ct);
                        logger.LogWarning("pdftoppm failed: {Error}. Trying direct Tesseract on PDF.", error);
                        return await OcrPdfDirectly(pdfPath, ct).ConfigureAwait(false);
                    }
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "pdftoppm not available, trying direct Tesseract on PDF");
                    return await OcrPdfDirectly(pdfPath, ct).ConfigureAwait(false);
                }
            }

            // 2. Obtener y ordenar correctamente las páginas
            var pageFiles = Directory.GetFiles(tempDir, "page-*.png")
                .OrderBy(GetPageNumber) // Ordenación numérica real
                .ToList();

            if (pageFiles.Count == 0)
            {
                logger.LogWarning("No pages generated by pdftoppm. Trying direct Tesseract.");
                return await OcrPdfDirectly(pdfPath, ct).ConfigureAwait(false);
            }

            // 3. Procesamiento en Paralelo Controlado
            var tasks = new List<Task<(int Index, string Text)>>();
            using var semaphore = new SemaphoreSlim(MaxParallelPages);

            for (int i = 0; i < pageFiles.Count; i++)
            {
                int index = i; 
                string pageFile = pageFiles[i];

                tasks.Add(Task.Run(async () =>
                {
                    await semaphore.WaitAsync(ct);
                    try
                    {
                        var text = await OcrImageAsync(pageFile, ct);
                        return (Index: index, Text: text);
                    }
                    finally
                    {
                        semaphore.Release();
                    }
                }, ct));
            }

            var results = await Task.WhenAll(tasks);

            // 4. Reconstruir el documento manteniendo el orden correcto
            var finalStructuredText = new StringBuilder();
            foreach (var result in results.OrderBy(r => r.Index))
            {
                finalStructuredText.AppendLine(result.Text);
            }

            logger.LogInformation("OCR completed, extracted {Length} characters", finalStructuredText.Length);
            return finalStructuredText.ToString();
        }
        finally
        {
            // Limpieza segura del directorio temporal
            try
            {
                if (Directory.Exists(tempDir))
                    Directory.Delete(tempDir, true);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Failed to delete temporary directory {Path}", tempDir);
            }
        }
    }

    private static async Task<string> OcrPdfDirectly(string pdfPath, CancellationToken ct)
    {
        using var tesseractProcess = new Process();
        tesseractProcess.StartInfo = new ProcessStartInfo
        {
            FileName = "tesseract",
            Arguments = $"\"{pdfPath}\" stdout -l eng",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        tesseractProcess.Start();
        var output = await tesseractProcess.StandardOutput.ReadToEndAsync(ct).ConfigureAwait(false);
        await tesseractProcess.WaitForExitAsync(ct).ConfigureAwait(false);

        return tesseractProcess.ExitCode == 0 ? output : string.Empty;
    }

    private static async Task<string> OcrImageAsync(string imagePath, CancellationToken ct)
    {
        using var process = new Process();
        process.StartInfo = new ProcessStartInfo
        {
            FileName = "tesseract",
            Arguments = $"\"{imagePath}\" stdout -l eng",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        process.Start();
        var output = await process.StandardOutput.ReadToEndAsync(ct).ConfigureAwait(false);
        await process.WaitForExitAsync(ct).ConfigureAwait(false);

        return output ?? string.Empty;
    }

    private static int GetPageNumber(string filePath)
    {
        // Extrae el número del archivo (ej: "page-05.png" -> 5) para ordenar numéricamente
        var match = Regex.Match(Path.GetFileName(filePath), @"\d+");
        return match.Success && int.TryParse(match.Value, out var num) ? num : 0;
    }
}